spring.application.name=Manh
# DB config
spring.datasource.url=jdbc:sqlserver://DESKTOP-UCU2GN1\\SQLEXPRESS;databaseName=BaiTap05;integratedSecurity=true;encrypt=false
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA config
spring.jpa.hibernate.ddl-auto=update  # Tự động tạo/update table
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Upload file config
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ... (cấu hình DB trước đó giữ nguyên)

# Security config
spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=ADMIN
